version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eventlet
    versions:
    - 0.30.0
    - 0.30.1
  - dependency-name: gunicorn
    versions:
    - 20.0.4
